<a href="https://colab.research.google.com/github/muneeswarikagitala-web/meenu/blob/main/numpy_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[1 2 3 4 5]
 [4 5 6 7 8]]
[ 5  7  9 11 13]
[15 30]


In [ ]:
l=[10,20,30,40]#1d array indexing
arr=np.array(l)
print(arr[3])
print(arr[0])
print(arr[1])
print(arr[-1])

40
10
20
40


In [ ]:
l2=np.array([   #indexing in array of matrix
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[1,0])
print(l2[0])
print(l2[1])
print(l2[2])
print(l2[:,0])
print(l2[:,1])
print(l2[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
4
[1 2 3]
[4 5 6]
[7 8 9]
[1 4 7]
[2 5 8]
[3 6 9]


In [ ]:
#slicing [start:end:step] 1d
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
print(arr[0:2])
print(arr[0:5])
print(arr[1:5])
print(arr[0:5:2])
print(arr[1:])
print(arr[:4])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[2 3 4 5]
[1 3 5]
[2 3 4 5]
[1 2 3 4]


In [ ]:
#slicing [row_start:row_end,col_start:col_end] 2d
l=np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11]
])
print(l)
print(l[0:2,0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]]
